<a href="https://colab.research.google.com/github/AarohSinha100/DEEP_LEARNING/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we are going to cover some of the most fundamental concepts of tensors using tensorflow


# Intoduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7) #Creates a constant tensor from a tensor-like object.
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim #Dimension

1

In [ ]:
#Create a matrix (has more than 1 dimensions)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim #Dimension

2

In [ ]:
#Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16) #specifying the datatype with dtype
another_matrix
#shape - (3,2) means 3 rows 2 columns

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's create a tensor - more than 2 dimensions
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      
                      [[7,8,9],
                       [10,11,12]],
                      
                      [[13,14,15],
                       [16,17,18]]])

tensor
#shape - (3,2,3) 

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim


3

# Creating with tf.variable()

In [ ]:
#Creating the same Tensors with tf.Variable() as above

changeble_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changeble_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Changing one of the element in changebl tensor
changeble_tensor[0] = 7
changeble_tensor

TypeError: ignored

In [ ]:
#How abot we try .assign()
changeble_tensor[0].assign(7)
changeble_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#contant tensors can't be changed.

# Creating Random Tensors

In [ ]:
# Create two random (but same) tensors

random_1 = tf.random.Generator.from_seed(42) #set seed for reproducability
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42) #set seed for reproducability
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1, random_2 , random_1 == random_2 #if seeds are same then the tensors are same

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the order of the elements in a tensor

#### Shuffling is necessary as random inputs to the neural networs is good! eg - first 5000 cat images and then 4000 dog images is bad. But both of them shuffled are good

In [ ]:
#unSsuffled tensor
not_shuffled = tf.constant([[10,7],
                            [3,5],
                            [2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 2,  5]], dtype=int32)>

In [ ]:
#Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled) #shuffled in order of dimension. Inner elements are not getting shuffled.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  5],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) #Global level random seed
tf.random.shuffle(not_shuffled,seed=42) #Operation level random seed
#To use shuffled tensors in the same order we need global level random seeds and operation level random seeds together.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  5]], dtype=int32)>

# Creating Tensor from Numpy Arrays

In [ ]:
#create a tensor of all ones
tf.ones(shape=(10,7)) #shape

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#create a tensors of all zeros
tf.zeros(shape=(5,5)) #shape

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#You can also turn numpy arrays to tensorflow tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) #create a NumPy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A,shape=(3,4,2))
B

<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

# Gettind Information from Tensors (Shape,rank,Axis or dimension,Size)

In [ ]:
#Create a rank (ndim) 4 Tensor
rank_4_tensor = tf.zeros(shape = [2,3,4,5]) #shape parameter
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[0,1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
rank_4_tensor[0,1,1]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor) #size = 2x3x4x5 = 120

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#Get various attributes of our tensors
print("Datatype of every element:",rank_4_tensor.dtype) 
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("Shape of tensor:",tf.shape(rank_4_tensor))
print("Elements along the 0 axis - ",rank_4_tensor.shape[0])
print("Elements along the last azis",rank_4_tensor.shape[-1])
print("Total elements of our tensor:",tf.size(rank_4_tensor))

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
Elements along the 0 axis -  2
Elements along the last azis 5
Total elements of our tensor: tf.Tensor(120, shape=(), dtype=int32)


In [ ]:
#create shape to a integer
tf.size(rank_4_tensor).numpy()

120

# Indexing and expanding tensors

In [ ]:
#Tensors can be indexed like Python list

In [ ]:
#Get the first 2 elements in each dimensions of rank_4_tensors
rank_4_tensor[:2,:2,:2,:2] #:2 from each dimension (we have 4 dimension)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first elemeneet from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:] #colon means get the entire stuff.

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim, tf.size(rank_2_tensor)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
#last item of each row of rank 2 tensor
rank_2_tensor[:,-1] #:1 for each dimension

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

#### ADD AN EXTRA DIMENSION


In [ ]:
#Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Expand 0 axis
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

# Manipulating Tensors (Tensor Operations)

In [ ]:
#You can add values to the tensor using addition operators
my_tensor = tf.constant([[10,7],[3,4]])
my_tensor+10 #10 gets added to all the elements out there and the original tensor remains unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
my_tensor #THE ORIGINAL TENSOR REMAINS UNCHANGED

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#Multiplication also works (This is scalar multiplication)
my_tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
my_tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
#We can use the tensorflow built in function too
tf.multiply(my_tensor,10) #Multiplication
#Original tensor still remains unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.add(my_tensor,244)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[254, 251],
       [247, 248]], dtype=int32)>

# Matrix Multiplication - One of most common tensor application.

In [ ]:
#To multiply a matrix with other matrix we need to do the dot product of one column with another column.
#Dot product - Multiplying numbers and matching them up. (look at - matrixmultiplication.xyz)

#Matrix multiplication is diffrent form normal multiplication like tensor * tensor.

In [ ]:
#Matrix multiplication in TensorFlow
print(my_tensor)
tf.matmul(my_tensor, my_tensor) #Matrix multiplication of a tensor by itself

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Example - 
tf1 = tf.constant([[[1,2,5],
                   [7,2,1],
                   [3,3,3]]])
tf2 = tf.constant([[[3,5],
                    [6,7],
                    [1,8]]])
tf.matmul(tf1,tf2)

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[20, 59],
        [34, 57],
        [30, 60]]], dtype=int32)>

In [ ]:
#Matrix multiplication with the python operator "@"
my_tensor @ my_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Rules for tensor or matrices need to fulfill if ew have to matrrix multiply them
# 1 - The inner dimesions must match
# 2 - The resulting matrix has the shape of the outer dimensions

'''eg shape1 = [2,3] shape2 = [2,3]
  2*2 not equals 3*3
  but if,
        shape1 = [2,3] shape2 = [3,2]
        2*3 === 3*2
'''

'eg shape1 = [2,3] shape2 = [2,3]\n  2*2 not equals 3*3\n  but if,\n        shape1 = [2,3] shape2 = [3,2]\n        2*3 === 3*2\n'

In [ ]:
#reshape a tensor - 
#tf.reshape(tensor, shape = (x,y))

In [ ]:
#reshaping with transpose
my_tensor, tf.transpose(my_tensor), tf.reshape(my_tensor,shape=(1,4))
#resize  -resizes the element and transpose also shuffles it while also changing the shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  3],
        [ 7,  4]], dtype=int32)>,
 <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[10,  7,  3,  4]], dtype=int32)>)

In [ ]:
# tf.tensordot(tf.transpose(X),y,axes=1)

# Changing the datatype of tensors

In [ ]:
#Default datatype of most tensors will be int32

In [ ]:
#Creating a new tensor with a default datatype float32
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
#Change from float 32 to float 16 (reduced precission)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

# TensorFlow Aggregation (Finding mean, max, mean and more)


In [ ]:
#Get the absolute values - absolute values means take all the negetive numbers and turn it into positive numbers
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
#Creatin g a random tensor between 0 to 100 of size 50
E = tf.constant(np.random.randint(1,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([98,  8, 42, 53, 89, 26, 52, 98, 61, 91, 53, 83, 51, 38, 33, 84, 99,
       32, 15, 22, 17, 17, 30, 78,  5,  5,  2,  3, 47, 24, 21, 15, 61, 91,
       14, 84, 13, 45,  9, 86, 90, 58, 66,  9, 24, 31,  4, 78, 31, 23])>

In [ ]:
tf.size(E) , E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#Minimum number - 
tf.reduce_min(E).numpy()

2

In [ ]:
#Max
tf.reduce_max(E).numpy()

99

In [ ]:
#Mean
tf.reduce_mean(E).numpy()

44

In [ ]:
#Sum
tf.reduce_sum(E).numpy()

2209

In [ ]:
#To find the vairance of our tensor we need to acces the tensorflow probability
#Variance
import tensorflow_probability as tfp
tfp.stats.variance(E).numpy()

960

In [ ]:
#Standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32)).numpy()

30.985603

# Find the positional minimum and maximum

In [ ]:
#Create a new tensor for finding the positional minimum and maximum
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional maximum
tf.argmax(F).numpy()

42

In [ ]:
#Index our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Check for equality just to be safe
F[tf.argmax(F)] == tf.reduce_max(F) #True

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
#Finding the positional minimum
tf.argmin(F).numpy()

16

In [ ]:
#Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# Squeexing a tensors (removing all simgle dimensions)

In [ ]:
#Creating a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G) #will remove all dimension-1
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
G_squeezed.shape, G.shape #Note that G_squeezed doesnot has any 1 dimensions

(TensorShape([50]), TensorShape([1, 1, 1, 1, 50]))

##One-hot encoder Tensors


In [ ]:
#Create a list of indices
some_list = [0,1,2,3]

#One hot encode our list of in=dices 
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo I love leep learning",off_value="I also like to dance") #on value = 1, offvalue=0

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love leep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love leep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love leep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love leep learning']],
      dtype=object)>

# Some more tensor math operations

In [ ]:
#Create a new Tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Square root
tf.math.sqrt(tf.cast(H, dtype=tf.float32)) #sqrt doesnot takes intm so cast to float

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#Find the log
tf.math.log(tf.cast(H,dtype=tf.float32)) #log doesnot takes intm so cast to float

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

Finding Access to GPU



In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU") #nw shows our cpu and gpu (follow the course vide. kch kch krna pdega iske liye settings se)

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Tue Apr 11 14:56:42 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------